import React, { useState } from 'react'

function TyreDealer() {


    const [selectedItemType, setSelectedItemType] = useState("");

  
    const itemTypes = [
        { name: "Mumbai" },
        { name: "Delhi" },
        { name: "Kolkata" },
        { name: "Chennai" },
        { name: "Bangalore" },
        { name: "Hyderabad" },
        { name: "Ahmedabad" },
        { name: "Pune" },
        { name: "Surat" },
        { name: "Kanpur" },
        { name: "Jaipur" },
        { name: "Lucknow" },
        { name: "Nagpur" },
        { name: "Visakhapatnam" },
        { name: "Indore" },
        { name: "Coimbatore" },
        { name: "Kochi" },
        { name: "Patna" },
        { name: "Vadodara" },
        { name: "Bhopal" },
        { name: "Thane" },
        { name: "Agra" },
        { name: "Nashik" },
        { name: "Faridabad" },
        { name: "Meerut" },
        { name: "Rajkot" },
        { name: "Kalyan-Dombivli" },
        { name: "Vasai-Virar" },
        { name: "Varanasi" },
        { name: "Srinagar" },
        { name: "Amritsar" },
        { name: "Navi Mumbai" },
        { name: "Dhanbad" },
        { name: "Allahabad" },
        { name: "Ranchi" },
        { name: "Mysore" },
        { name: "Guwahati" },
        { name: "Jodhpur" },
        { name: "Bhubaneswar" },
        { name: "Salem" },
        { name: "Warangal" },
        { name: "Mangalore" },
        { name: "Jabalpur" },
        { name: "Gwalior" },
        { name: "Raipur" },
        { name: "Kota" },
        { name: "Bareilly" },
        { name: "Karnal" },
        { name: "Udaipur" },
        { name: "Siliguri" },
        { name: "Tiruchirappalli" },
        { name: "Bikaner" },
        { name: "Jamshedpur" },
        { name: "Dehradun" },
        { name: "Rourkela" },
        { name: "Durgapur" },
        { name: "Nanded" },
        { name: "Bhatinda" },
        { name: "Ambala" },
        { name: "Kalyan" },
        { name: "Bilaspur" },
        { name: "Asansol" },
        { name: "Patiala" },
        { name: "Sangli" },
        { name: "Kota" },
        { name: "Haldwani" },
        { name: "Nashik" },
        { name: "Tirupati" },
        { name: "Kochi" },
        { name: "Gurgaon" },
        { name: "Noida" },
        { name: "Dharamshala" },
        { name: "Shimla" },
        { name: "Kangra" },
        { name: "Mandi" },
        { name: "Sirmaur" },
        { name: "Solan" },
        { name: "Hamirpur" },
        { name: "Una" },
        { name: "Nahan" },
        { name: "Palampur" },
        { name: "Kinnaur" },
        { name: "Chamba" },
        { name: "Bilaspur" },
        { name: "Kinnaur" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Fatehabad" },
        { name: "Sirsa" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Jind" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Karnal" },
        { name: "Hissar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
        { name: "Bhiwani" },
        { name: "Mahendragarh" },
        { name: "Rewari" },
        { name: "Gurgaon" },
        { name: "Faridabad" },
        { name: "Ambala" },
        { name: "Yamunanagar" },
        { name: "Panchkula" },
        { name: "Kurukshetra" },
        { name: "Kaithal" },
        { name: "Jind" },
        { name: "Sirsa" },
        { name: "Fatehabad" },
        { name: "Hisar" },
        { name: "Rohtak" },
        { name: "Sonipat" },
    ]

  const Change = (e) => {
    setSelectedItemType(e.target.value);
  };


  return (
    <div className='flex flex-col md:flex-row h-[15rem] md:h-48 justify-between h-48 border-2 border-solid border-black-500 w-full p-2 bg-[#ffffff]'>
      <div className='md:w-8/12 w-95 flex flex-col gap-3'>
        <div className='flex justify-start'>
            <p className='text-black-800 font-medium text-xl'>Search Tyre Dealer in Your City</p>
        </div>
        <div className='flex gap-2 ml-2 md:flex-wrap '>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>New Delhi</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Ahmedabad</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Gurgaon</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Mumbai</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Kolkata</p>
        </div>
        <div className='flex gap-2 items-center ml-2 md:flex-wrap'>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Chennai</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Pune</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Lucknow</p>
            <p className='h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Hyderabad</p>
            <p className=' h-10 w-32 text-left pl-2 pt-2 border-2 border-solid border-black-500 text-blue-800 font-medium text-sm cursor-pointer'>Navi Mumbai</p>
        </div>
      </div>
      <div className='w-[95%] md:w-3/12 flex justify-center items-center '>
        <div className='flex flex-col gap-3 w-full'>
            <div className='flex justify-start'>
                <p >Search tyre in other city</p>
            </div>
            
            <select className='border-2 border-solid border-black-500 pt-2 pb-2 pl-3 pr-3 w-full' value={selectedItemType} onChange={Change}>
                <option value="">Select an item type</option>
                {itemTypes.map((type,index) => (
                <option key={index} value={type.name}>
                    {type.name}
                </option>
                ))}
            </select>
        </div>
      </div>
    </div>
  )
}

export default TyreDealer;




